import{S as M,a as m,i as v}from"./assets/vendor-c145bea9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const t={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),searchBtn:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),loader:document.querySelector(".loader")},p=new M(".gallery-item a",{captionsData:"alt",captionDelay:250});m.defaults.baseURL="https://pixabay.com/api";const q="41834264-e3d0e5d80121a8a176d918e74",n="is-hidden";let c=1,d="",y=0;t.form.addEventListener("submit",S);async function S(r){if(r.preventDefault(),t.gallery.innerHTML="",c=1,t.loadMoreBtn.classList.add(n),d=t.form.query.value.trim(),!d){u("The search field can't be empty! Please, enter your request!");return}try{const{hits:o,totalHits:a}=await h(d);y=Math.ceil(a/40),g(o),p.refresh(),o.length>0?(t.loadMoreBtn.classList.remove(n),t.loadMoreBtn.addEventListener("click",B)):(t.loadMoreBtn.classList.add(n),u("Sorry, there are no images matching your search query. Please, try again!")),f(!1)}catch(o){console.log(o)}finally{t.form.reset(),c===y&&(t.loadMoreBtn.classList.add(n),u("We're sorry, but you've reached the end of search results!"))}}async function B(){c+=1;try{f(!0),t.loadMoreBtn.classList.add(n);const{hits:r}=await h(d,c);g(r),p.refresh(),f(!1),w(),t.loadMoreBtn.classList.remove(n)}catch(r){console.log(r)}finally{c===y&&(t.loadMoreBtn.classList.add(n),u("We're sorry, but you've reached the end of search results!"))}}async function h(r,o=1){f(!0);try{return(await m.get("/",{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data}catch(a){console.log()(a)}}function g(r){const o=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:s,views:l,comments:L,downloads:b})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${a}"
      alt="${e}"
    />
    <p class="gallery-descr">likes: <span class="descr-span">${s}</span> views: <span class="descr-span">${l}</span> comments: <span class="descr-span">${L}</span> downloads: <span class="descr-span">${b}</span></p>
  </a>
</li>`).join("");t.gallery.insertAdjacentHTML("beforeend",o)}function u(r){v.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function f(r=!0){t.loader.style.display=r?"inline-block":"none"}function w(){const r=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
